### ISSUE TITLE
Please add a license to your code

### ISSUE THREAD

**Issue by Gimly** [MSiccDev/XfMvvmLight#1]
Hi,

Thanks a lot for this very useful sample project, it helped me a lot in understanding how to bootstrap a Xamarin app with MVVM Light.

Would you mind adding a license (if possible MIT) to your code so that it can more easily be shared and reinterpreted?

Thanks!

**Comment by MSiccDev** [comment]
glad my sample is helpful. I just added the MIT License to that project.
